# Generated by Django 5.0 on 2023-12-13 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker_API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='purchase_price',
        ),
    ]
