# Generated by Django 5.0 on 2023-12-13 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker_API', '0002_remove_portfolio_purchase_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='description',
        ),
    ]
